import java.util.List;

public class TelaVisualizarIngresso extends javax.swing.JFrame {
    Ingresso i;
    /**
     * Creates new form TelaVisualizarIngresso
     */
    public TelaVisualizarIngresso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite seu CPF");

        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MENU INICIAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        ManagerCSV managerCSV = new ManagerCSV();
        String cpf = txtcpf.getText();

        // Flag de checagem
        boolean foundMatch = false;

        // Variáveis ingresso
        String horarioSessao = null;
        String nomeFilme = null;
        String salaFilme = null;
        String nomePessoa = null;
        int idadePessoa = 0;
        String cpfPessoa = null;
        String tipoPessoa = null;
        String assento = null;
        double preco = 0;

        List matrizIngressos = managerCSV.csvParaMatrizJava(managerCSV.getFileIngressos());
        for (int i = 0; i < matrizIngressos.size(); i++) {
            List linhaMatriz = (List) matrizIngressos.get(i);

            for (int j = 0; j < linhaMatriz.size(); j++) {
                if (linhaMatriz.get(0).equals(cpf)) {
                    foundMatch = true;
                    cpfPessoa = cpf;
                    switch (j) {
                        case 1 -> nomePessoa = (String) linhaMatriz.get(j);
                        case 2 -> idadePessoa = Integer.parseInt((String) linhaMatriz.get(j));
                        case 3 -> horarioSessao = (String) linhaMatriz.get(j);
                        case 4 -> nomeFilme = (String) linhaMatriz.get(j);
                        case 5 -> salaFilme = (String) linhaMatriz.get(j);
                        case 6 -> assento = (String) linhaMatriz.get(j);
                        case 7 -> tipoPessoa = (String) linhaMatriz.get(j);
                        case 8 -> preco = Double.parseDouble((String) linhaMatriz.get(j));
                    }
                }
            }
            if (foundMatch) break;
        }

        if (foundMatch) {
            Sessao sessao = new Sessao(nomeFilme, salaFilme, horarioSessao, 100, true, preco);
            Ingresso ingresso = new Ingresso(idadePessoa, nomePessoa, cpfPessoa, tipoPessoa, sessao, assento, preco);
            TelaVisualizandoIngresso tvi = new TelaVisualizandoIngresso(ingresso);
            this.dispose();
            tvi.setVisible(true);
        }
    }

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        TelaIngresso ti = new TelaIngresso();
        this.dispose();
        ti.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisualizarIngresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtcpf;
    // End of variables declaration//GEN-END:variables
}
